# Generated by Django 5.0.3 on 2024-03-24 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wall', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reply',
            name='confirm',
            field=models.CharField(choices=[('unknown', 'На рассмотрении'), ('confirmed', 'Принят'), ('cancelled', 'Отклонен')], default='unknown', max_length=16),
        ),
    ]
